apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-cluster
spec:
  steps:
    - name: clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
      script: |
        #!/bin/sh
        cd /work
        git clone "https://github.com/tdolby-at-uk-ibm-com/ace-pipeline-demo-21-02"
      volumeMounts:
        - mountPath: /work
          name: work
    - name: deploy-app
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/work/ace-pipeline-demo-21-02/tekton/tea-tekton-deployment.yaml"
      volumeMounts:
        - mountPath: /work
          name: work
    - name: create-service
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/work/ace-pipeline-demo-21-02/tekton/tea-tekton-service.yaml"
      volumeMounts:
        - mountPath: /work
          name: work
  volumes:
    - name: work
      emptyDir: {}
