apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-pipeline
spec:
  params:
    - name: dockerRegistry
      type: string
  tasks:
    - name: build-from-source
      taskRef:
        name: maven-ace-build
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
    - name: deploy-to-cluster
      taskRef:
        name: deploy-to-cluster
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
      runAfter:
        - build-from-source
